name: flutter_iexcloud_api
description: Flutter API Client for IEX Cloud.
version: 1.0.0
author: Tiarê Balbi Bonamini <@tiarebalbi>
homepage: https://github.com/tiarebalbi/flutter_iexcloud_api

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.17.3
  test_coverage: ^0.5.0

flutter: null
