name: flutter_iexcloud_api
description: Flutter API Client to retrieve financial data using IEX Cloud data provider.
version: 1.0.2
homepage: https://github.com/tiarebalbi/flutter_iexcloud_api
issue_tracker: https://github.com/tiarebalbi/flutter_iexcloud_api/issues

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=5.0.0 <6.0.0"

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
