name: flutter_iexcloud_api
description: Flutter API Client to retrieve financial data using IEX Cloud data provider.
version: 1.0.0
author: Tiarê Balbi Bonamini <@tiarebalbi>
homepage: https://github.com/tiarebalbi/flutter_iexcloud_api
issue_tracker: https://github.com/tiarebalbi/flutter_iexcloud_api/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0